services:
  api:
    profiles:
      - app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=yourlawyer
      - JWT_SECRET=your-super-secret-key-here
      - JWT_EXPIRATION=1d
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev

  postgres:
    image: postgres:15-alpine
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=yourauth
    profiles:
      - infra
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data

  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - '6379:6379'
  #   profiles:
  #     - infra

volumes:
  postgres_data:
